FROM  golang:1.16-alpine
# 描述
LABEL description="golang 1.16"

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    GOPATH=/www/go \ 
    GOPROXY="https://proxy.golang.com.cn,direct" \
    GO111MODULE=on



